version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data  # ✅ Correct volume syntax

  api:
    build: 
      context: ../server
      dockerfile: Dockerfile  # ✅ Match the actual filename case
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db  # ✅ Space after dash

  client:
    build: 
      context: ../client
      dockerfile: Dockerfile  # ✅ Match actual filename
    ports:
      - "5173:5173"
    depends_on:
      - api  # ✅ Space after dash

volumes:
  db_data:
