
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: prefin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # ✅ Correct volume syntax

  api:
    build: 
      context: ../server
      dockerfile: Dockerfile  # ✅ Match the actual filename case
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB:PORT: 5432
      DB_NAME: prefin
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db  # ✅ Space after dash

  client:
    build: 
      context: ../client
      dockerfile: Dockerfile  # ✅ Match actual filename
    ports:
      - "5173:5173"
    depends_on:
      - api  # ✅ Space after dash

volumes:
  db_data:
